config/routes.rb
Rails.application.routes.draw do
  resources :cryptos
  devise_for :users
  get 'home/about'
  get 'home/lookup'
  post '/home/lookup' => '/home/lookup'
  root 'home#index'

end

app/models/crypto.rb
class Crypto < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :cryptos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  before_action :set_crypto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit,:update,:destroy, :show]
  # GET /cryptos
  # GET /cryptos.json
  def index
    @cryptos = Crypto.all
    require 'json'
    require 'net/http'
    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @coins = JSON.parse(@response)
  end

  # GET /cryptos/1
  # GET /cryptos/1.json
  def show
  end

  # GET /cryptos/new
  def new
    @crypto = Crypto.new
  end

  # GET /cryptos/1/edit
  def edit
  end

  # POST /cryptos
  # POST /cryptos.json
  def create
    @crypto = Crypto.new(crypto_params)

    respond_to do |format|
      if @crypto.save
        format.html { redirect_to @crypto, notice: 'Crypto was successfully created.' }
        format.json { render :show, status: :created, location: @crypto }
      else
        format.html { render :new }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptos/1
  # PATCH/PUT /cryptos/1.json
  def update
    respond_to do |format|
      if @crypto.update(crypto_params)
        format.html { redirect_to @crypto, notice: 'Crypto was successfully updated.' }
        format.json { render :show, status: :ok, location: @crypto }
      else
        format.html { render :edit }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptos/1
  # DELETE /cryptos/1.json
  def destroy
    @crypto.destroy
    respond_to do |format|
      format.html { redirect_to cryptos_url, notice: 'Crypto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crypto
      @crypto = Crypto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crypto_params
      params.require(:crypto).permit(:symbol, :user_id, :cost_per, :amount_owned)
    end
    
    def correct_user
      @correct = current_user.cryptos.find_by(id: params[:id])
      redirect_to cryptos_path, notice:"You aren't authorized to modify this entry!!" if @correct.nil?
    end
    
    def number_to_indian_currency(number) 
      if number string = number.to_s.split('.') 
       number = string[0].gsub(/(\d+)(\d{3})$/){ p = $2;"#{$1.reverse.gsub(/(\d{2})/,'\1,').reverse},#{p}"} 
       number = number.gsub(/^,/, '') + '.' + string[1] if string[1] # remove leading comma 
       number = number[1..-1] if number[0] == 44  
      end 
     "Rs.#{number}" 
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'json'
    require 'net/http'
    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @coins = JSON.parse(@response)
    @select_coins = ["BTC", "LTC", "XMR", "ADA"]
    
  end
  
  def about
    @var = "jagadish.dachepalli@gmail.com"
  end
  
  def lookup
    @var = params[:id]
    if @var
      @var = @var.upcase
    end
    
    if @var == ''
      @var = "Please enter some crypto currency type"
    end
    # require 'json'
    # require 'net/http'
    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @coins = JSON.parse(@response)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cryptos/_form.html.erb
<%= form_for(@crypto) do |f| %>
  <% if @crypto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crypto.errors.count, "error") %> prohibited this crypto from being saved:</h2>

      <ul>
      <% @crypto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :symbol %><br>
    <%= f.text_field :symbol %>
  </div>
  <div class="field">
    <!--<%= f.label :user_id %><br>-->
    <%= f.number_field :user_id , value:current_user.id , type:"hidden" %>
  </div>
  <div class="field">
    <%= f.label :cost_per %><br>
    <%= f.text_field :cost_per %>
  </div>
  <div class="field">
    <%= f.label :amount_owned %><br>
    <%= f.text_field :amount_owned %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cryptos/edit.html.erb
<h1>Editing Crypto</h1>

<%= render 'form' %>

<%= link_to 'Show', @crypto %> |
<%= link_to 'Back', cryptos_path %>

app/views/cryptos/index.html.erb
<!--<p id="notice"><%= notice %></p>-->
<% profit_loss = 0 %>
<h1>Listing Cryptos</h1>
<table class="table table-hover">
  <thead>
    <tr class="success">
      <th>Name</th>
      <th>Current Price(USD)</th>
      <th>Current Total Value</th>
      <th>Purchased Total Value</th>
      <th>Profit / Loss</th>
      <th>Symbol</th>
      <!--<th>User</th>-->
      <th>Cost paid per</th>
      <th>Amount owned</th>
    </tr>
  </thead>

  <tbody>
    <% @cryptos.each do |crypto| %>
    <% if crypto.user_id == current_user.id %>
      <% for x in @coins %>
        <% if crypto.symbol %>
          <% crypto.symbol = crypto.symbol.upcase %>
        <% end %>
        
        <% if crypto.symbol == x["symbol"] %>
        <tr>
            <td><%= link_to x["name"],  crypto %></td>
            <td>$<%= x["price_usd"] %></td>
            <td>$<%= x["price_usd"].to_d * crypto.amount_owned%> </td>
            <td>$<%= crypto.cost_per * crypto.amount_owned%> </td>
            <td>$<%= (x["price_usd"].to_d * crypto.amount_owned) - (crypto.cost_per * crypto.amount_owned)  %> </td>
            <% profit_loss += (x["price_usd"].to_d * crypto.amount_owned) - (crypto.cost_per * crypto.amount_owned)%>
            <!--rank: <%= x["rank"] %> <br/>-->
            <!--price: $<%= x["price_usd"] %> <br/>-->
            <!--change: <%= x["percent_change_24h"] %> <br/>-->
            <!--updated : <%= x["last_updated"] %> <br/>-->
            <br/>    
        <% end %>
      <%end%>
      
        <td><%= crypto.symbol %></td>
        <!--<td><%= crypto.user_id %></td>-->
        <td>$<%= crypto.cost_per %></td>
        <td><%= crypto.amount_owned %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>


<br/>
<br/>
<strong>Portfolio profit/loss -</strong> <%= number_to_currency(profit_loss) %>
<br/>
<br/>
<%= link_to 'New Crypto', new_crypto_path, class:"btn btn-success" %>

app/views/cryptos/new.html.erb
<h1>New Crypto</h1>

<%= render 'form' %>

<%= link_to 'Back', cryptos_path %>

app/views/cryptos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Symbol:</strong>
  <%= @crypto.symbol %>
</p>

<p>
  <strong>User:</strong>
  <%= @crypto.user_id %>
</p>

<p>
  <strong>Cost per:</strong>
  <%= @crypto.cost_per %>
</p>

<p>
  <strong>Amount owned:</strong>
  <%= @crypto.amount_owned %>
</p>

<%= link_to 'Edit', edit_crypto_path(@crypto) %> |
<%= link_to 'Back', cryptos_path %> |
<%= link_to 'Delete', crypto_path(@crypto), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
    <div class="alert alert-warning alert-dismissible">
        <button class="close" data-dismiss="alert">
            <i class="glyphicon glyphicon-remove-circle"></i>
        </button>
        <%= content_tag(:div, msg) %>
        
    </div>
<% end %>    

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to "Crypto Portfolio", root_path , class:"navbar-brand"%>

      <!--<a class="navbar-brand" href="#">Crypto Prtfolio</a>-->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!--<ul class="nav navbar-nav">-->
      <!--  <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>-->
      <!--  <li><a href="#">Link</a></li>-->
        <!--<li class="dropdown">-->
        <!--  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
        <!--  <ul class="dropdown-menu">-->
        <!--    <li><a href="#">Action</a></li>-->
        <!--    <li><a href="#">Another action</a></li>-->
        <!--    <li><a href="#">Something else here</a></li>-->
        <!--    <li role="separator" class="divider"></li>-->
        <!--    <li><a href="#">Separated link</a></li>-->
        <!--    <li role="separator" class="divider"></li>-->
        <!--    <li><a href="#">One more separated link</a></li>-->
        <!--  </ul>-->
        <!--</li>-->
      <!--</ul>-->
      <!--<form class="navbar-form navbar-left">-->
      <!--  <div class="form-group">-->
      <!--    <input type="text" class="form-control" placeholder="Search">-->
      <!--  </div>-->
      <!--  <button type="submit" class="btn btn-default">Submit</button>-->
      <!--</form>-->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %> </li>
        <li><%= link_to "About", home_about_path %></li>
        <li><%= link_to "Lookup",home_lookup_path %></li>
        
        <% if user_signed_in? %>
          <li><%= link_to "Logout",destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Edit",edit_user_registration_path %></li>  
          <li><%= link_to "Add_crypto", new_crypto_path %></li>
          <li><%= link_to "List_cryptos", cryptos_path %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login",new_user_session_path %></li>
        <% end %>
        <!--<li class="dropdown">-->
        <!--  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
        <!--  <ul class="dropdown-menu">-->
        <!--    <li><a href="#">Action</a></li>-->
        <!--    <li><a href="#">Another action</a></li>-->
        <!--    <li><a href="#">Something else here</a></li>-->
        <!--    <li role="separator" class="divider"></li>-->
        <!--    <li><a href="#">Separated link</a></li>-->
        <!--  </ul>-->
        <!--</li>-->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<H1 text-align="center"> About us </H1>

<p> This site is for people who wants to check the latest news on crypto coins and for people who loves to earn money by investing in crypto currency..</p>

<p>For any queries, contact me @<%= @var %></p>

app/views/home/index.html.erb
<h1>Home</h1>
<hr>
This is the landing page for crypto currency portfolio
</br>
</br>
<button type="button" class="btn btn-primary">Click to invest</button>
<br/>
<% @coins %>

<% for x in @coins %>
    <% for coin in @select_coins %>
        <% if coin == x["symbol"] %>
            Name: <%= x["name"] %> <br/>
            rank: <%= x["rank"] %> <br/>
            price: $<%= x["price_usd"] %> <br/>
            change: <%= x["percent_change_24h"] %> <br/>
            updated : <%= x["last_updated"] %> <br/>
            <br/>    
        <% end %>
        
    <% end %>
<%end%>


<div class="footer">
    <hr>
  <p>copyrights reserved @Jagadish &copy;2018-2020</p>
</div>










<!DOCTYPE html>
<!--<html lang="en">-->

<!--  <head>-->

<!--    <meta charset="utf-8">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">-->
<!--    <meta name="description" content="">-->
<!--    <meta name="author" content="">-->

<!--    <title>Landing Page - Start Bootstrap Theme</title>-->

    <!-- Bootstrap core CSS -->
<!--    <link href="app/assests/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">-->

    <!-- Custom fonts for this template -->
<!--    <link href="app/assests/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">-->
<!--    <link href="app/assests/vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css">-->
<!--    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">-->

    <!-- Custom styles for this template -->
<!--    <link href="app/assests/stylesheets/landing-page.min.css" rel="stylesheet">-->
<!--    <link href="app/assests/stylesheets/landing-page.css" rel="stylesheet">-->

<!--  </head>-->

<!--  <body>-->

    <!-- Navigation -->
<!--    <nav class="navbar navbar-light bg-light static-top">-->
<!--      <div class="container">-->
<!--        <a class="navbar-brand" href="#">Start Bootstrap</a>-->
<!--        <a class="btn btn-primary" href="#">Sign In</a>-->
<!--      </div>-->
<!--    </nav>-->

    <!-- Masthead -->
<!--    <header class="masthead text-white text-center">-->
<!--      <div class="overlay"></div>-->
<!--      <div class="container">-->
<!--        <div class="row">-->
<!--          <div class="col-xl-9 mx-auto">-->
<!--            <h1 class="mb-5">Build a landing page for your business or project and generate more leads!</h1>-->
<!--          </div>-->
<!--          <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">-->
<!--            <form>-->
<!--              <div class="form-row">-->
<!--                <div class="col-12 col-md-9 mb-2 mb-md-0">-->
<!--                  <input type="email" class="form-control form-control-lg" placeholder="Enter your email...">-->
<!--                </div>-->
<!--                <div class="col-12 col-md-3">-->
<!--                  <button type="submit" class="btn btn-block btn-lg btn-primary">Sign up!</button>-->
<!--                </div>-->
<!--              </div>-->
<!--            </form>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--    </header>-->

    <!-- Icons Grid -->
<!--    <section class="features-icons bg-light text-center">-->
<!--      <div class="container">-->
<!--        <div class="row">-->
<!--          <div class="col-lg-4">-->
<!--            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">-->
<!--              <div class="features-icons-icon d-flex">-->
<!--                <i class="icon-screen-desktop m-auto text-primary"></i>-->
<!--              </div>-->
<!--              <h3>Fully Responsive</h3>-->
<!--              <p class="lead mb-0">This theme will look great on any device, no matter the size!</p>-->
<!--            </div>-->
<!--          </div>-->
<!--          <div class="col-lg-4">-->
<!--            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">-->
<!--              <div class="features-icons-icon d-flex">-->
<!--                <i class="icon-layers m-auto text-primary"></i>-->
<!--              </div>-->
<!--              <h3>Bootstrap 4 Ready</h3>-->
<!--              <p class="lead mb-0">Featuring the latest build of the new Bootstrap 4 framework!</p>-->
<!--            </div>-->
<!--          </div>-->
<!--          <div class="col-lg-4">-->
<!--            <div class="features-icons-item mx-auto mb-0 mb-lg-3">-->
<!--              <div class="features-icons-icon d-flex">-->
<!--                <i class="icon-check m-auto text-primary"></i>-->
<!--              </div>-->
<!--              <h3>Easy to Use</h3>-->
<!--              <p class="lead mb-0">Ready to use with your own content, or customize the source files!</p>-->
<!--            </div>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--    </section>-->

    <!-- Image Showcases -->
<!--    <section class="showcase">-->
<!--      <div class="container-fluid p-0">-->
<!--        <div class="row no-gutters">-->

<!--          <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('images/bg-showcase-1.jpg');"></div>-->
<!--          <div class="col-lg-6 order-lg-1 my-auto showcase-text">-->
<!--            <h2>Fully Responsive Design</h2>-->
<!--            <p class="lead mb-0">When you use a theme created by Start Bootstrap, you know that the theme will look great on any device, whether it's a phone, tablet, or desktop the page will behave responsively!</p>-->
<!--          </div>-->
<!--        </div>-->
<!--        <div class="row no-gutters">-->
<!--          <div class="col-lg-6 text-white showcase-img" style="background-image: url('images/bg-showcase-2.jpg');"></div>-->
<!--          <div class="col-lg-6 my-auto showcase-text">-->
<!--            <h2>Updated For Bootstrap 4</h2>-->
<!--            <p class="lead mb-0">Newly improved, and full of great utility classes, Bootstrap 4 is leading the way in mobile responsive web development! All of the themes on Start Bootstrap are now using Bootstrap 4!</p>-->
<!--          </div>-->
<!--        </div>-->
<!--        <div class="row no-gutters">-->
<!--          <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('images/bg-showcase-3.jpg');"></div>-->
<!--          <div class="col-lg-6 order-lg-1 my-auto showcase-text">-->
<!--            <h2>Easy to Use &amp; Customize</h2>-->
<!--            <p class="lead mb-0">Landing Page is just HTML and CSS with a splash of SCSS for users who demand some deeper customization options. Out of the box, just add your content and images, and your new landing page will be ready to go!</p>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--    </section>-->

    <!-- Testimonials -->
<!--    <section class="testimonials text-center bg-light">-->
<!--      <div class="container">-->
<!--        <h2 class="mb-5">What people are saying...</h2>-->
<!--        <div class="row">-->
<!--          <div class="col-lg-4">-->
<!--            <div class="testimonial-item mx-auto mb-5 mb-lg-0">-->
<!--              <img class="img-fluid rounded-circle mb-3" src="images/testimonials-1.jpg" alt="">-->
<!--              <h5>Margaret E.</h5>-->
<!--              <p class="font-weight-light mb-0">"This is fantastic! Thanks so much guys!"</p>-->
<!--            </div>-->
<!--          </div>-->
<!--          <div class="col-lg-4">-->
<!--            <div class="testimonial-item mx-auto mb-5 mb-lg-0">-->
<!--              <img class="img-fluid rounded-circle mb-3" src="images/testimonials-2.jpg" alt="">-->
<!--              <h5>Fred S.</h5>-->
<!--              <p class="font-weight-light mb-0">"Bootstrap is amazing. I've been using it to create lots of super nice landing pages."</p>-->
<!--            </div>-->
<!--          </div>-->
<!--          <div class="col-lg-4">-->
<!--            <div class="testimonial-item mx-auto mb-5 mb-lg-0">-->
<!--              <img class="img-fluid rounded-circle mb-3" src="images/testimonials-3.jpg" alt="">-->
<!--              <h5>Sarah	W.</h5>-->
<!--              <p class="font-weight-light mb-0">"Thanks so much for making these free resources available to us!"</p>-->
<!--            </div>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--    </section>-->

    <!-- Call to Action -->
<!--    <section class="call-to-action text-white text-center">-->
<!--      <div class="overlay"></div>-->
<!--      <div class="container">-->
<!--        <div class="row">-->
<!--          <div class="col-xl-9 mx-auto">-->
<!--            <h2 class="mb-4">Ready to get started? Sign up now!</h2>-->
<!--          </div>-->
<!--          <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">-->
<!--            <form>-->
<!--              <div class="form-row">-->
<!--                <div class="col-12 col-md-9 mb-2 mb-md-0">-->
<!--                  <input type="email" class="form-control form-control-lg" placeholder="Enter your email...">-->
<!--                </div>-->
<!--                <div class="col-12 col-md-3">-->
<!--                  <button type="submit" class="btn btn-block btn-lg btn-primary">Sign up!</button>-->
<!--                </div>-->
<!--              </div>-->
<!--            </form>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--    </section>-->

    <!-- Footer -->
<!--    <footer class="footer bg-light">-->
<!--      <div class="container">-->
<!--        <div class="row">-->
<!--          <div class="col-lg-6 h-100 text-center text-lg-left my-auto">-->
<!--            <ul class="list-inline mb-2">-->
<!--              <li class="list-inline-item">-->
<!--                <a href="#">About</a>-->
<!--              </li>-->
<!--              <li class="list-inline-item">&sdot;</li>-->
<!--              <li class="list-inline-item">-->
<!--                <a href="#">Contact</a>-->
<!--              </li>-->
<!--              <li class="list-inline-item">&sdot;</li>-->
<!--              <li class="list-inline-item">-->
<!--                <a href="#">Terms of Use</a>-->
<!--              </li>-->
<!--              <li class="list-inline-item">&sdot;</li>-->
<!--              <li class="list-inline-item">-->
<!--                <a href="#">Privacy Policy</a>-->
<!--              </li>-->
<!--            </ul>-->
<!--            <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2018. All Rights Reserved.</p>-->
<!--          </div>-->
<!--          <div class="col-lg-6 h-100 text-center text-lg-right my-auto">-->
<!--            <ul class="list-inline mb-0">-->
<!--              <li class="list-inline-item mr-3">-->
<!--                <a href="#">-->
<!--                  <i class="fa fa-facebook fa-2x fa-fw"></i>-->
<!--                </a>-->
<!--              </li>-->
<!--              <li class="list-inline-item mr-3">-->
<!--                <a href="#">-->
<!--                  <i class="fa fa-twitter fa-2x fa-fw"></i>-->
<!--                </a>-->
<!--              </li>-->
<!--              <li class="list-inline-item">-->
<!--                <a href="#">-->
<!--                  <i class="fa fa-instagram fa-2x fa-fw"></i>-->
<!--                </a>-->
<!--              </li>-->
<!--            </ul>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--    </footer>-->

    <!-- Bootstrap core JavaScript -->
<!--    <script src="app/assests/vendor/jquery/jquery.min.js"></script>-->
<!--    <script src="app/assests/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>-->

<!--  </body>-->

<!--</html>-->

app/views/home/lookup.html.erb
<h3>Search for individual Crypto Currency</h3>

<%= form_tag home_lookup_path, :method => 'POST' do %>
    <%= text_field_tag 'id', nil, placeholder: 'Enter Cyrpto currency symbol', size:50 %>
    <%= submit_tag 'Lookup stock status' %>
<% end %>
<br/>
<% @coins %>
<% @var %>
<!--<% @temp = 0 %>-->
<% if @var == "Please enter some crypto currency type" %>
    <%@var="please enter some value" %>
    <%= @var %>
<%end%>
<% for x in @coins %>
    <% if @var == x["symbol"] %>
        Name: <%= x["name"] %> <br/>
            rank: <%= x["rank"] %> <br/>
            price: $<%= x["price_usd"] %> <br/>
            change: <%= x["percent_change_24h"] %> <br/>
            updated : <%= x["last_updated"] %> <br/>
    <% end %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crypto Currency Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--<meta name="viewport" content="width=device-width, initial-scale=1">-->
  <meta name="viewport" content="width=device-width, initial-scale=10, maximum-scale=10, user-scalable=no">

</head>
<body>

<!--<a href="/" >Home</a> | <a href="home/about">About us</a>-->
<%= render 'home/navbar' %>
<div class="container">
  <%= render 'home/flash' %>
  <%= yield %>
</div>


</body>
</html>